apiVersion: v1
kind: PersistentVolume
metadata:
    name: datadir-mysql-0
    namespace: galera-mysql
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  nfs:
    path: /data/datadir-mysql-0
    server: 192.168.43.200
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: datadir-mysql-1
    namespace: galera-mysql
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  nfs:
    path: /data/datadir-mysql-1
    server: 192.168.43.201
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: datadir-mysql-2
    namespace: galera-mysql
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  nfs:
    path: /data/datadir-mysql-2
    server: 192.168.43.202   
