apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc-volume
  namespace: galera-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
